# Kulibrat Game Configuration

# Game settings
game:
  board_rows: 4
  board_cols: 3
  initial_pieces: 4
  target_score: 5
  ai_delay: 0.5  # Reduced delay for faster gameplay

# User interface configuration
ui:
  interface: pygame  # Options: console, pygame
  screen_width: 1024
  screen_height: 768

# Player configuration
players:
  player_1:
    type: human  # Options: human, minimax, random, mcts, genetic_minimax
    color: black
  player_2:
    type: mcts
    color: red

# AI Strategies Configuration
strategies:
  minimax:
    time_limit: 2.5  # Time limit in seconds for move calculation
    max_depth: 20     # Maximum depth (safety limit)
    use_alpha_beta: true
    heuristic: score_diff
    tt_size: 1000000  # Transposition table size
  
  mcts:
    simulation_time: 2.5
    max_iterations: 200000
    exploration_weight: 2.5 # The bigger the value, the more exploration
    
  random: {}
