output:
  results_dir: tournament_results
  save_csv: true
  save_plots: true
players:
- exploration_weight: 0.49584547744752405
  name: MCTS-0.50
  type: mcts
tournament:
  matches_per_pairing: 25
  max_turns: 80
  target_score: 5
